import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {

  const handleSubmit = (event) => {
    event.preventDefault(event);
  }
  return (
    <>
      <Head>
        <title>To-do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleSubmit} className={styles.form}>
          <input
            className={styles.input}
            type="text"
            // value={text}
            // onChange={(event) => setText(event.target.value)}
            placeholder="Add Todo..."
          />
          <button className={styles.btn}>
            Add
          </button>
        </form>
        <div className={styles.todos}>
          {/* <div className={styles.todo}>
            <p>Go shopping</p>
            <button className={styles.todoBtn}>
              X
            </button>
          </div>
          <div className={styles.todo}>
            <p>Go shopping and go for lunch</p>
            <button className={styles.todoBtn}>
              X
            </button>
          </div>
          <div className={styles.todo}>
            <p>Go shopping and then gor a run with a friend</p>
            <button className={styles.todoBtn}>
              X
            </button>
          </div> */}
        </div>
      </main>
    </>
  )
}
